/*
  GENERATED by scripts/measure-badge-art.mjs -- do not edit by hand.

  Where each badge's artwork is drawn on its canvas, as insets from the
  top, right, bottom and left edges in percent. The coin clips its plate
  and rim to these, so they never show past the artwork's own frame.
*/

export type ArtBounds = readonly [top: number, right: number, bottom: number, left: number];

export const BADGE_ART_BOUNDS: Readonly<Record<string, ArtBounds>> = {
  'archipelago': [10.4, 10.7, 15.2, 11.3],
  'business': [9.6, 14.8, 12.5, 15],
  'caffeine': [12.5, 12.9, 15, 13.9],
  'culture': [11.7, 12.5, 14.1, 12.3],
  'direct-booker': [9, 13.5, 10.2, 13.1],
  'early-riser': [12.9, 13.1, 15.8, 13.3],
  'estate-explorer': [11.5, 10.5, 14.6, 10.7],
  'family': [6.8, 11.3, 8.4, 11.5],
  'first-look': [16.4, 15.6, 15.6, 15.6],
  'foodie': [8.4, 8.2, 10, 8.2],
  'full-estate': [11.5, 11.5, 14.5, 11.7],
  'good-notes': [12.3, 12.9, 15.6, 12.9],
  'group': [8.4, 13.1, 11.3, 13.1],
  'homecoming': [11.3, 11.5, 14.3, 11.5],
  'homegrown': [11.3, 12.1, 12.9, 12.1],
  'host': [9.6, 13.5, 12.3, 14.3],
  'in-training': [12.3, 12.7, 13.9, 12.7],
  'island-hopper': [11.5, 11.7, 13.9, 12.1],
  'long-stay': [10.5, 15.2, 10.5, 15.6],
  'luzon-to-mindanao': [10, 9.6, 13.3, 9.8],
  'maker': [8.2, 10.2, 11.7, 10],
  'menu-explorer': [25.6, 9.2, 26, 9.2],
  'new-opening': [9.4, 10.7, 14.1, 10.7],
  'night-owl': [12.9, 13.1, 14.5, 13.1],
  'outdoors': [12.9, 13.3, 14.8, 12.3],
  'pair': [9.4, 14.5, 12.3, 15],
  'planner': [5.5, 10.9, 8.6, 10.9],
  'pre-checked': [7.2, 12.9, 9, 13.1],
  'regular': [11.1, 14.5, 10.2, 14.5],
  'room-service': [11.7, 12.9, 14.6, 12.5],
  'scanned-in': [17, 17, 17.2, 17.2],
  'sea-legs': [12.9, 13.3, 13.3, 12.9],
  'self-sufficient': [14.3, 15, 18, 15],
  'solo': [9.8, 15.4, 11.7, 15.6],
  'spontaneous': [10.9, 14.5, 10.5, 15.2],
  'sundowner': [10, 11.1, 12.9, 10.7],
  'switched': [10.9, 13.5, 12.9, 14.1],
  'venue-opener': [25.8, 10.2, 27.1, 10.2],
  'venue-regular': [24.4, 9.4, 24.2, 9.2],
  'weekender': [10.4, 14.6, 10.7, 15],
  'well-groomed': [10, 12.1, 13.9, 11.7],
  'wellness': [12.1, 13.3, 15, 12.3],
};
