"""Outline the stay pass seal's ring lettering into
src/components/features/guest-app/stamp-lettering.ts.

Run from the repo root after changing the words, sizes or font:
    python3 scripts/stamp-lettering.py > src/components/features/guest-app/stamp-lettering.ts
Needs fonttools and brotli (pip install fonttools brotli).
"""
import math, json, sys
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen

font = instantiateVariableFont(TTFont('public/fonts/AsbirSans-Variable.woff2'), {'wght': 800, 'opsz': 14})
upm = font['head'].unitsPerEm
cmap = font.getBestCmap(); gs = font.getGlyphSet(); hmtx = font['hmtx']

def arc_text(text, size, length, centre_deg, r=33.0):
    scale = size / upm
    names = [cmap[ord(c)] for c in text]
    adv = [hmtx[n][0] * scale for n in names]
    extra = (length - sum(adv)) / (len(text) - 1)   # lengthAdjust="spacing"
    pen = SVGPathPen(gs, ntos=lambda v: f"{v:.2f}".rstrip('0').rstrip('.'))
    s = -length / 2
    for name, a in zip(names, adv):
        mid = s + a / 2
        ang = math.radians(centre_deg) + mid / r
        x, y = 50 + r * math.cos(ang), 50 + r * math.sin(ang)
        rot = ang + math.pi / 2
        c, si = math.cos(rot), math.sin(rot)
        # glyph units -> local (centred on its advance, y down) -> rotate -> place
        m = (c * scale, si * scale, si * scale, -c * scale, 0, 0)
        # local x' = (gx - a_units/2)*scale ; y' = -gy*scale ; then rotate
        ox = -(a / 2)
        tx = x + c * ox
        ty = y + si * ox
        tp = TransformPen(pen, (c * scale, si * scale, si * scale * 1, -c * scale, tx, ty))
        gs[name].draw(tp)
        s += a + extra
    return pen.getCommands()

top = arc_text('CABANA', 6.6, 34, -90)
bottom = arc_text('VERIFIED STAY', 5.4, 38, 90)
print(f"""/*
  Generated by scripts/stamp-lettering.py -- do not edit by hand.

  The stay pass seal's ring lettering as outlines, not SVG text: Asbir Sans
  at weight 800, laid along the seal's 33-unit arcs exactly as the old
  <textPath> set them. Live SVG text was laid out apart from the shapes
  around it, so while the stamp animated the words lagged and slid off the
  disc; outlines move with the seal as one piece.
*/
export const STAMP_LETTERING_TOP = '{top}';
export const STAMP_LETTERING_BOTTOM = '{bottom}';""")
