"""Outline the stay pass seal's ring lettering into
src/components/features/guest-app/stamp-lettering.ts.

Run from the repo root after changing the words, sizes or fonts:
    python3 scripts/stamp-lettering.py > src/components/features/guest-app/stamp-lettering.ts
Needs fonttools and brotli (pip install fonttools brotli).

Fonts: public/fonts/AsbirSans-Variable.woff2 (the app's sans) and
scripts/fonts/Newsreader-Latin.woff2 (the app's serif, the Latin subset
next/font serves; Newsreader is under the SIL Open Font License).
"""
import math
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen


def load(path, axes):
    font = instantiateVariableFont(TTFont(path), axes)
    return font, font.getBestCmap(), font.getGlyphSet(), font['hmtx'], font['head'].unitsPerEm


def ring(font, text, size, tracking, radius, centre, outward):
    """Set `text` on a circle about (50, 50), centred on `centre` degrees.

    outward=True reads clockwise with the letters' tops facing out (the top
    of a seal); outward=False reads left to right along the bottom with the
    tops facing in, so neither word is ever upside down.
    """
    _, cmap, glyphs, hmtx, upm = font
    scale = size / upm
    names = [cmap[ord(c)] for c in text]
    advances = [hmtx[n][0] * scale for n in names]
    track = tracking * size
    length = sum(advances) + track * (len(text) - 1)
    pen = SVGPathPen(glyphs, ntos=lambda v: f"{v:.2f}".rstrip('0').rstrip('.'))
    s = -length / 2
    for name, advance in zip(names, advances):
        mid = s + advance / 2
        theta = math.radians(centre) + (mid / radius if outward else -mid / radius)
        cos, sin = math.cos(theta), math.sin(theta)
        px, py = 50 + radius * cos, 50 + radius * sin
        # Reading direction along the arc, and the letters' "up".
        ax, ay = (-sin, cos) if outward else (sin, -cos)
        ux, uy = (cos, sin) if outward else (-cos, -sin)
        # Font units have y up; each glyph is centred on its own advance.
        dx, dy = px - ax * advance / 2, py - ay * advance / 2
        glyphs[name].draw(TransformPen(pen, (ax * scale, ay * scale, ux * scale, uy * scale, dx, dy)))
        s += advance + track
    return pen.getCommands()


serif = load('scripts/fonts/Newsreader-Latin.woff2', {'wght': 480})
sans = load('public/fonts/AsbirSans-Variable.woff2', {'wght': 600, 'opsz': 14})

# The lettering band runs between the rings at r=25 and r=39.6.
top = ring(serif, 'CABANA', 8.6, 0.34, 29.6, -90, outward=True)
bottom = ring(sans, 'VERIFIED STAY', 4.2, 0.42, 34.3, 90, outward=False)

print(f"""/*
  Generated by scripts/stamp-lettering.py -- do not edit by hand.

  The stay pass seal's ring lettering as outlines, not SVG text, so it moves
  with the seal as one piece (live SVG text was laid out apart from the
  shapes around it and slid off the disc while the stamp animated).
  CABANA in the Newsreader serif, widely tracked, over the top; VERIFIED
  STAY in small tracked Asbir Sans along the bottom, reading upright.
*/
export const STAMP_LETTERING_TOP = '{top}';
export const STAMP_LETTERING_BOTTOM = '{bottom}';""")
